//local host
http://localhost:8080/contacts
################################################
//render
GET https://cse341-2.onrender.com/contacts/632de84ae1475b0db72e424a

###################################################
###CREATE NEW CONTACT
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Nicole",
    "lastName": "Littlefield",
    "email": "lnicole@gmail.com",
    "favoriteColor": "pink",
    "birthday": "09/01/1999"
}

###################################################
###UPDATE CONTACT

PUT http://localhost:8080/contacts/632de84ae1475b0db72e424a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Nicole",
    "lastName": "Littlefield",
    "email": "nicolelit@gmail.com",
    "favoriteColor": "pink",
    "birthday": "09/01/1999"
}

###################################################
###DELETE CONTACT

DELETE http://localhost:8080/contacts/632de84ae1475b0db72e424a HTTP/1.1


